// function fn() {
//   try {
//     let a
//     let a
//   } catch (error) {
//     return 1;
//   } finally {
//     return 2;
//   }
// }

// console.log(fn());  // 2

// throw 1
// throw true
// throw 'error'
// throw { a: 1 }

// try{
//     throw 1
// }catch(error){
//     console.log(error);
// }